# Site settings
title:
email: wedding@satuhearty.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.satuhearty.com" # the base hostname & protocol for your site

username: satuhearty

# Build settings
markdown: kramdown

sass:
  sass_dir: ./_sass
  style:    compressed

gems:
  - jekyll-sitemap